name: Build .exe

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4
            
            -   name: Setup Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'

            -   name: Install dependencies
                run: pip install pyinstaller

            -   name: Create example config.env
                run: echo GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} > config.env

            -   name: Build .exe
                run: pyinstaller --onedir --windowed --add-data "styles/styles.qss;styles" --add-data "config.env;." --add-data "default_settings.py;." main.py

            -   name: Upload .exe to GitHub
                uses: actions/upload-artifact@v4
                with:
                    name: latest-exe
                    path: dist\main\main.exe